### ISSUE TITLE
出现这个信息“ 群: XXXXX 帐号:XXXX  操作者帐号:XXXXX  设置禁言 有效期: 60秒” 会报错

### ISSUE THREAD

**Issue by shitianshiwa** [CaoMeiYouRen/bili-dynamic-forward#4]
20:42:55.142 -> [WebSocket] 连线出现了error！！
s [UnexpectedContextError]: Unexpected context is received.
    at Function._handle (/home/user/coolq/bili2/index.js:4640:62)
    at d.a (/home/user/coolq/bili2/index.js:4711:53)
    at d.i [as dispatchEvent] (/home/user/coolq/bili2/index.js:22374:42)
    at d.p (/home/user/coolq/bili2/index.js:22212:34)
    at h.<anonymous> (/home/user/coolq/bili2/index.js:22194:19)
    at h.emit (events.js:315:20)
    at h.processFrame (/home/user/coolq/bili2/index.js:4920:80)
    at /home/user/coolq/bili2/index.js:4874:27
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  context: {
    duration: 60,
    group_id:XXXXXXX ,
    notice_type: 'unknown',
    operator_id:XXXXXXX ,
    post_type: 'notice',
    self_id:XXXXXXX ,
    sub_type: 'ban',
    time: 1593952974,
    user_id:XXXXXXX 
  },
  reason: 'unexpected "notice_type"'
}

**Comment by shitianshiwa** [comment]
运行环境 docker版酷Q
https://github.com/shitianshiwa/docker-wine-coolq-dotnet48-autoins
coolq-http-api = 4.12.0
httpapi 插件分身版 https://github.com/yuudi/yobot/blob/97f6ee2a9c833dd4e16127c1414186571f08a268/documents/install/Windows-portable.md
这个httpapi版本应该有群内单人禁言
https://cqhttp.cc/docs/4.12/#/API?id=set_group_ban-%E7%BE%A4%E7%BB%84%E5%8D%95%E4%BA%BA%E7%A6%81%E8%A8%80
node = 12.18.0

**Comment by shitianshiwa** [comment]
如果可以的话，希望添加群聊启用开关（分群管理）、私聊屏蔽名单、转发内容可选开关功能

**Comment by CaoMeiYouRen** [comment]
> 20:42:55.142 -> [WebSocket] 连线出现了error！！
> s [UnexpectedContextError]: Unexpected context is received.
> at Function._handle (/home/user/coolq/bili2/index.js:4640:62)
> at d.a (/home/user/coolq/bili2/index.js:4711:53)
> at d.i [as dispatchEvent] (/home/user/coolq/bili2/index.js:22374:42)
> at d.p (/home/user/coolq/bili2/index.js:22212:34)
> at h. (/home/user/coolq/bili2/index.js:22194:19)
> at h.emit (events.js:315:20)
> at h.processFrame (/home/user/coolq/bili2/index.js:4920:80)
> at /home/user/coolq/bili2/index.js:4874:27
> at processTicksAndRejections (internal/process/task_queues.js:79:11) {
> context: {
> duration: 60,
> group_id:XXXXXXX ,
> notice_type: 'unknown',
> operator_id:XXXXXXX ,
> post_type: 'notice',
> self_id:XXXXXXX ,
> sub_type: 'ban',
> time: 1593952974,
> user_id:XXXXXXX
> },
> reason: 'unexpected "notice_type"'
> }

这个问题应该是上游依赖 `cq-websocket`的问题了，我记得以前修复过这个问题，有空排查下。

**Comment by CaoMeiYouRen** [comment]
> 如果可以的话，希望添加群聊启用开关（分群管理）、私聊屏蔽名单、转发内容可选开关功能

设计插件的时候没想那么多，以后有空的话会考虑加上。

**Comment by CaoMeiYouRen** [comment]
> 20:42:55.142 -> [WebSocket] 连线出现了error！！
> s [UnexpectedContextError]: Unexpected context is received.
> at Function._handle (/home/user/coolq/bili2/index.js:4640:62)
> at d.a (/home/user/coolq/bili2/index.js:4711:53)
> at d.i [as dispatchEvent] (/home/user/coolq/bili2/index.js:22374:42)
> at d.p (/home/user/coolq/bili2/index.js:22212:34)
> at h. (/home/user/coolq/bili2/index.js:22194:19)
> at h.emit (events.js:315:20)
> at h.processFrame (/home/user/coolq/bili2/index.js:4920:80)
> at /home/user/coolq/bili2/index.js:4874:27
> at processTicksAndRejections (internal/process/task_queues.js:79:11) {
> context: {
> duration: 60,
> group_id:XXXXXXX ,
> notice_type: 'unknown',
> operator_id:XXXXXXX ,
> post_type: 'notice',
> self_id:XXXXXXX ,
> sub_type: 'ban',
> time: 1593952974,
> user_id:XXXXXXX
> },
> reason: 'unexpected "notice_type"'
> }

我自己试了下无法复现你这个BUG，我估计是 `coolq-http-api` 的问题了

**Comment by shitianshiwa** [comment]
> > 20:42:55.142 -> [WebSocket] 连线出现了error！！
> > s [UnexpectedContextError]: Unexpected context is received.
> > at Function._handle (/home/user/coolq/bili2/index.js:4640:62)
> > at d.a (/home/user/coolq/bili2/index.js:4711:53)
> > at d.i [as dispatchEvent] (/home/user/coolq/bili2/index.js:22374:42)
> > at d.p (/home/user/coolq/bili2/index.js:22212:34)
> > at h. (/home/user/coolq/bili2/index.js:22194:19)
> > at h.emit (events.js:315:20)
> > at h.processFrame (/home/user/coolq/bili2/index.js:4920:80)
> > at /home/user/coolq/bili2/index.js:4874:27
> > at processTicksAndRejections (internal/process/task_queues.js:79:11) {
> > context: {
> > duration: 60,
> > group_id:XXXXXXX ,
> > notice_type: 'unknown',
> > operator_id:XXXXXXX ,
> > post_type: 'notice',
> > self_id:XXXXXXX ,
> > sub_type: 'ban',
> > time: 1593952974,
> > user_id:XXXXXXX
> > },
> > reason: 'unexpected "notice_type"'
> > }
> 
> 我自己试了下无法复现你这个BUG，我估计是 `coolq-http-api` 的问题了

是版本低了，要4.13.0才行
https://github.com/richardchien/coolq-http-api/releases/tag/v4.13.0
更新日志：

/get_credentials 接口新增 domain 参数，和 /get_cookies 相同，表示要获取的 cookies 的域
HTTP 接口支持 CORS，添加配置项 enable_cors 为 true，即可从浏览器跨域访问，Fix #246
修复群禁言事件 notice_type 为 unknown 的 bug，Fix #262
优化增强 CQ 码出错时的提示，Fix #263
